In [9]:
import pandas as pd
import glob
import os
from os.path import abspath

In [47]:
'''Retrieve and read last stored csv file'''
data_path = abspath('./data/')
lst = os.listdir(data_path)
lst.sort(reverse=True)

dir = lst[0]
dir_path = data_path + '/' + dir 
file_path = glob.glob(dir_path + '/*')[0]

df = pd.read_csv(file_path)
df.sort_values(by='ranking')

,IMBd_id,title,ranking,ranking_name,released_year,duration_min,genre,collected_at
200,tt0111161,Les Évadés,1,top_250,1994,142min,Drama,2021-11-02 12:13:19.809484
201,tt0068646,Le Parrain,2,top_250,1972,175min,"Crime,Drama",2021-11-02 12:13:19.810297
202,tt0468569,The Dark Knight : Le Chevalier noir,3,top_250,2008,152min,"Action,Crime,Drama",2021-11-02 12:13:19.811124
203,tt0071562,"Le Parrain, 2ᵉ partie",4,top_250,1974,202min,"Crime,Drama",2021-11-02 12:13:19.811985
204,tt0050083,12 Hommes en colère,5,top_250,1957,96min,"Crime,Drama",2021-11-02 12:13:19.812796
...,...,...,...,...,...,...,...,...
145,tt0031679,Mr. Smith au sénat,246,top_250,1939,129min,"Comedy,Drama",2021-11-02 12:13:23.881627
146,tt0031381,Autant en emporte le vent,247,top_250,1939,238min,"Drama,History,Romance",2021-11-02 12:13:23.882546
147,tt0025316,New York - Miami,248,top_250,1934,105min,"Comedy,Romance",2021-11-02 12:13:23.883724
148,tt0019254,La passion de Jeanne d'Arc,249,top_250,1928,110min,"Biography,Drama,History",2021-11-02 12:13:23.884539
149,tt0017925,Le mécano de la Générale,250,top_250,1926,67min,"Action,Adventure,Comedy",2021-11-02 12:13:23.885369